
import React, { useState } from 'react';
import { motion } from 'framer-motion';
import { 
  CheckCircle2, 
  AlertCircle, 
  Lightbulb, 
  Target, 
  TrendingUp,
  FileText,
  Search,
  ChevronRight,
  ShieldAlert,
  Wrench,
  AlertTriangle,
  Download,
  Loader2
} from 'lucide-react';
import { ResumeAnalysis } from '../types';
import { PieChart, Pie, Cell, ResponsiveContainer, Tooltip } from 'recharts';

interface AnalysisViewProps {
  analysis: ResumeAnalysis;
}

export const AnalysisView: React.FC<AnalysisViewProps> = ({ analysis }) => {
  const [isDownloading, setIsDownloading] = useState(false);

  const chartData = [
    { name: 'ATS Score', value: analysis.atsScore, color: '#0ea5e9' },
    { name: 'Formatting', value: analysis.formattingScore, color: '#8b5cf6' },
    { name: 'Keyword Match', value: analysis.keywordMatchScore, color: '#10b981' },
  ];

  const containerVariants = {
    hidden: { opacity: 0, y: 20 },
    visible: {
      opacity: 1,
      y: 0,
      transition: {
        staggerChildren: 0.1
      }
    }
  };

  const itemVariants = {
    hidden: { opacity: 0, scale: 0.95 },
    visible: { opacity: 1, scale: 1 }
  };

  const getImpactColor = (impact: string) => {
    switch (impact) {
      case 'High': return 'text-red-500 bg-red-50 dark:bg-red-900/20 border-red-200 dark:border-red-800';
      case 'Medium': return 'text-amber-500 bg-amber-50 dark:bg-amber-900/20 border-amber-200 dark:border-amber-800';
      default: return 'text-blue-500 bg-blue-50 dark:bg-blue-900/20 border-blue-200 dark:border-blue-800';
    }
  };

  const handleDownloadReport = () => {
    setIsDownloading(true);
    
    // Simulate a brief delay for a better "processing" feel
    setTimeout(() => {
      const reportContent = `
==================================================
ELEVATE AI - RESUME AUDIT REPORT
==================================================
Target Role: ${analysis.jobTitleMatch || 'Professional Candidate'}
Date: ${new Date().toLocaleDateString()}

OVERALL PERFORMANCE
--------------------------------------------------
ATS Compatibility Score: ${analysis.atsScore}%
Formatting Score: ${analysis.formattingScore}%
Keyword Match Score: ${analysis.keywordMatchScore}%

EXECUTIVE SUMMARY
--------------------------------------------------
${analysis.summary}

OPTIMIZATION WINS (STRENGTHS)
--------------------------------------------------
${analysis.strengths.map(s => `[✓] ${s}`).join('\n')}

ATS RED FLAGS (WEAKNESSES)
--------------------------------------------------
${analysis.weaknesses.map(w => `[!] ${w}`).join('\n')}

MISSING INDUSTRY KEYWORDS
--------------------------------------------------
${analysis.missingKeywords.join(', ')}

CRITICAL ADJUSTMENTS REQUIRED
--------------------------------------------------
${analysis.detailedCorrections.map((corr, idx) => `
${idx + 1}. ISSUE: ${corr.issue}
   IMPACT: ${corr.impact}
   FIX: ${corr.fix}
`).join('\n')}

SUGGESTIONS FOR IMPROVEMENT
--------------------------------------------------
${analysis.suggestions.map(s => `- ${s}`).join('\n')}

==================================================
Report generated by ElevateAI - Your Career Partner
==================================================
      `;

      const blob = new Blob([reportContent], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = `ElevateAI_Audit_${analysis.jobTitleMatch?.replace(/\s+/g, '_') || 'Report'}.txt`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);
      
      setIsDownloading(false);
    }, 1200);
  };

  return (
    <motion.div 
      className="space-y-8 pb-12"
      variants={containerVariants}
      initial="hidden"
      animate="visible"
    >
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Main Score Card */}
        <motion.div 
          variants={itemVariants}
          className="lg:col-span-1 p-8 rounded-3xl bg-white dark:bg-slate-800 shadow-xl border border-slate-200 dark:border-slate-700 flex flex-col items-center justify-center text-center relative overflow-hidden"
        >
          <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-primary-500 to-indigo-600"></div>
          <h3 className="text-xl font-black mb-6 flex items-center gap-2 text-black dark:text-white">
            <Target className="text-primary-500" /> ATS Compatibility
          </h3>
          <div className="relative w-56 h-56">
            <ResponsiveContainer width="100%" height="100%">
              <PieChart>
                <Pie
                  data={chartData}
                  cx="50%"
                  cy="50%"
                  innerRadius={70}
                  outerRadius={90}
                  paddingAngle={8}
                  dataKey="value"
                  stroke="none"
                >
                  {chartData.map((entry, index) => (
                    <Cell key={`cell-${index}`} fill={entry.color} />
                  ))}
                </Pie>
                <Tooltip />
              </PieChart>
            </ResponsiveContainer>
            <div className="absolute inset-0 flex flex-col items-center justify-center">
              <motion.span 
                initial={{ opacity: 0, scale: 0.5 }}
                animate={{ opacity: 1, scale: 1 }}
                className="text-5xl font-black text-black dark:text-white"
              >
                {analysis.atsScore}
              </motion.span>
              <span className="text-xs text-black dark:text-slate-500 uppercase font-black tracking-widest mt-1">Percentile</span>
            </div>
          </div>
          <p className="mt-6 text-sm text-black dark:text-slate-400 font-bold leading-relaxed">
            {analysis.summary}
          </p>
        </motion.div>

        {/* Detailed Feedback Cards */}
        <div className="lg:col-span-2 space-y-4">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <motion.div variants={itemVariants} className="p-6 rounded-3xl bg-emerald-50/50 dark:bg-emerald-900/10 border border-emerald-100 dark:border-emerald-800/50">
              <h4 className="font-black mb-4 flex items-center gap-2 text-emerald-600 dark:text-emerald-400 uppercase tracking-widest text-xs">
                <CheckCircle2 size={20} /> Optimization Wins
              </h4>
              <ul className="space-y-3">
                {analysis.strengths.slice(0, 3).map((s, i) => (
                  <li key={i} className="text-sm flex items-start gap-2">
                    <span className="w-1.5 h-1.5 rounded-full bg-emerald-400 mt-1.5 shrink-0" />
                    <span className="text-black dark:text-slate-300 font-bold">{s}</span>
                  </li>
                ))}
              </ul>
            </motion.div>
            
            <motion.div variants={itemVariants} className="p-6 rounded-3xl bg-red-50/50 dark:bg-red-900/10 border border-red-100 dark:border-red-800/50">
              <h4 className="font-black mb-4 flex items-center gap-2 text-red-600 dark:text-red-400 uppercase tracking-widest text-xs">
                <AlertCircle size={20} /> ATS Red Flags
              </h4>
              <ul className="space-y-3">
                {analysis.weaknesses.slice(0, 3).map((w, i) => (
                  <li key={i} className="text-sm flex items-start gap-2">
                    <span className="w-1.5 h-1.5 rounded-full bg-red-400 mt-1.5 shrink-0" />
                    <span className="text-black dark:text-slate-300 font-bold">{w}</span>
                  </li>
                ))}
              </ul>
            </motion.div>
          </div>

          <motion.div variants={itemVariants} className="p-6 rounded-3xl bg-white dark:bg-slate-800 shadow-lg border border-slate-200 dark:border-slate-700">
             <h3 className="text-lg font-black mb-4 flex items-center gap-2 text-black dark:text-white">
               <Search className="text-amber-500" /> Missing Industry Keywords
             </h3>
             <div className="flex flex-wrap gap-2">
               {analysis.missingKeywords.map((kw, i) => (
                 <span key={i} className="px-3 py-1.5 rounded-xl bg-slate-100 dark:bg-slate-700 text-black dark:text-slate-200 text-xs font-black border border-slate-200 dark:border-slate-600 hover:border-primary-400 transition-colors">
                   + {kw}
                 </span>
               ))}
             </div>
          </motion.div>
        </div>
      </div>

      {/* Detailed Corrections Section */}
      <motion.div variants={itemVariants} className="space-y-4">
        <h3 className="text-2xl font-black flex items-center gap-3 px-2 text-black dark:text-white">
          <ShieldAlert className="text-primary-500" /> Critical Adjustments Required
        </h3>
        
        <div className="grid grid-cols-1 gap-4">
          {analysis.detailedCorrections.map((corr, i) => (
            <motion.div 
              key={i}
              whileHover={{ x: 10 }}
              className="group grid grid-cols-1 md:grid-cols-12 gap-4 p-6 rounded-3xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 shadow-md hover:shadow-xl transition-all"
            >
              <div className="md:col-span-1 flex flex-col items-center justify-center">
                <span className={`px-2 py-1 rounded-lg text-[10px] font-black uppercase tracking-widest border mb-2 ${getImpactColor(corr.impact)}`}>
                  {corr.impact}
                </span>
                <div className="w-10 h-10 rounded-full bg-slate-50 dark:bg-slate-800 flex items-center justify-center text-slate-400 group-hover:text-primary-500 transition-colors">
                  <AlertTriangle size={20} />
                </div>
              </div>
              
              <div className="md:col-span-5 space-y-1">
                <h4 className="text-xs font-black text-black dark:text-slate-400 uppercase tracking-widest">What's Wrong</h4>
                <p className="text-black dark:text-white font-black leading-relaxed">{corr.issue}</p>
              </div>

              <div className="md:col-span-6 bg-primary-50/30 dark:bg-primary-900/10 p-4 rounded-2xl border border-primary-100 dark:border-primary-800/30">
                <h4 className="text-xs font-black text-primary-500 uppercase tracking-widest flex items-center gap-1 mb-1">
                  <Wrench size={12} /> The Fix
                </h4>
                <p className="text-black dark:text-slate-200 text-sm leading-relaxed italic font-bold">
                  "{corr.fix}"
                </p>
              </div>
            </motion.div>
          ))}
        </div>
      </motion.div>

      {/* Call to Action */}
      <motion.div 
        variants={itemVariants} 
        className="p-10 rounded-[2.5rem] bg-gradient-to-br from-slate-900 via-slate-800 to-indigo-950 text-white shadow-2xl relative overflow-hidden"
      >
        <div className="relative z-10 grid grid-cols-1 md:grid-cols-2 gap-8 items-center">
          <div>
            <h3 className="text-3xl font-black mb-4 flex items-center gap-3">
              Ready for the next step?
            </h3>
            <p className="text-slate-300 text-lg leading-relaxed max-w-md font-medium">
              Your profile for <span className="text-primary-400 font-black">{analysis.jobTitleMatch || 'Target Role'}</span> is strong. Applying these fixes will put you in the top 5% of candidates.
            </p>
          </div>
          <div className="flex flex-col sm:flex-row gap-4 justify-end">
            <button 
              onClick={handleDownloadReport}
              disabled={isDownloading}
              className="px-8 py-4 bg-primary-600 hover:bg-primary-500 text-white rounded-2xl font-black transition-all shadow-lg hover:scale-105 disabled:opacity-70 disabled:scale-100 flex items-center justify-center gap-2 min-w-[200px]"
            >
              {isDownloading ? (
                <>
                  <Loader2 size={20} className="animate-spin" />
                  Generating...
                </>
              ) : (
                <>
                  <Download size={20} />
                  Download Full Report
                </>
              )}
            </button>
            <button className="px-8 py-4 bg-white/10 hover:bg-white/20 backdrop-blur-md text-white border border-white/20 rounded-2xl font-black transition-all">
              Share Feedback
            </button>
          </div>
        </div>
        
        {/* Decorative background elements */}
        <div className="absolute -right-20 -bottom-20 w-80 h-80 bg-primary-500/10 rounded-full blur-[100px]"></div>
        <div className="absolute top-0 right-0 p-8 opacity-5">
          <TrendingUp size={200} />
        </div>
      </motion.div>
    </motion.div>
  );
};
